stages:
  - style
  - test

prettier:
  stage: style
  image: node:current-alpine

  before_script:
    - apk add git

  script:
    - yarn
    - yarn lint

jest:
  stage: test
  image: node:current-alpine

  before_script:
    - apk add git

  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn
    - yarn test:ci
